# Generated by Django 5.1.1 on 2025-01-15 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('IdentfyCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.assets')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tables')),
            ],
        ),
    ]
